name: Build Angular project
on:
  push:
    branches: ['staging']
  pull_request:
    branches: ['staging']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
